# Используем официальный образ PostgreSQL
FROM postgres:15-alpine

# Объявляем аргументы сборки
ARG POSTGRES_USER
ARG POSTGRES_PASSWORD
ARG POSTGRES_DB

# Устанавливаем переменные окружения на основе переданных аргументов
ENV POSTGRES_USER=${POSTGRES_USER}
ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
ENV POSTGRES_DB=${POSTGRES_DB}

# Открываем порт
EXPOSE 5432