version: '3.9'

services:
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    container_name: postgres_db
    env_file: .env
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    build:
      context: .
      dockerfile: pgadmin.Dockerfile
    container_name: postgres_admin
    env_file: .env
    depends_on:
      - db
    ports:
      - '5050:80'
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: backend
    env_file: .env
    ports:
      - '3000:3000'
    depends_on:
      - db
    restart: always

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile.nginx
    container_name: nginx
    ports:
      - '80:80'
    depends_on:
      - backend
      - pgadmin

volumes:
  postgres-data:
