version: '3.9'
services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    container_name: postgres_admin
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped
  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: 'Dockerfile'
    ports:
      - '3000:3000'
    environment:
      SERVER_PORT: ${SERVER_PORT}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
  nginx:
    image: nginx:alpine
    container_name: fullstack-app
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - pgadmin

volumes:
  postgres-data:
