[build]
builder = "DOCKERFILE"   # Use Docker for custom builds

# Specify Dockerfiles for each service
dockerfile = "Dockerfile.backend"  # Dockerfile for the backend service
pgadmin_dockerfile = "Dockerfile.pgadmin"  # Dockerfile for pgAdmin
nginx_dockerfile = "Dockerfile.nginx"  # Dockerfile for Nginx
db_dockerfile = "Dockerfile.db"  # Optional Dockerfile for PostgreSQL (if custom)

nixpacksPlan = { providers = ["node"] }  # Specify Node.js as the provider if your backend uses it

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10